#pragma once
#include "CoreMinimal.h"
#include "EEmotion.generated.h"

UENUM(BlueprintType)
enum class EEmotion : uint8 {
    DoNotUse,
    Angry,
    Annoyed,
    Anxious,
    Awkward,
    Conspiratorial,
    Despair,
    Drunk,
    Happy,
    Neutral,
    Proud,
    Sad,
    Shock,
    Skeptical,
    SlightlyAngry,
    SlightlyHappy,
    Smirk,
    Smolder,
    Thinking,
    WorkBench,
    Livid,
    SlightlyAnnoyed,
    LookDown,
    LookLeft,
    LookRight,
    LookUp,
    DrunkBar,
    Fear,
    Disgust,
    Injured,
    SmolderNew,
    Confused,
    Smug,
    Grimace,
    Yes,
    No,
    AngryPosture,
    RelaxedPosture,
    ReadDocumentPosture,
    Concerned,
    Agitated,
    NumEmotionStates,
};

