#pragma once
#include "CoreMinimal.h"
#include "EItemStat.generated.h"

UENUM(BlueprintType)
enum class EItemStat : uint8 {
    WeaponType,
    Damage,
    DPS,
    DamageType,
    DamageTypeEnumValue,
    DamageSpecialEffect,
    AmmoType,
    MagazineSize,
    RoF,
    AmmoPerShot,
    MaxChargeTime,
    SwingAttackRate,
    EquipTime,
    ReloadTime,
    ArmorPenetration,
    CriticalChance,
    CriticalMultiplier,
    WeakSpotMultiplier,
    SneakAttackMultiplier,
    EffectiveRange,
    NoiseRange,
    AoEOuterRadius,
    ArmorThresholdPhysical,
    ArmorResistancePhysical,
    ArmorThresholdPlasma,
    ArmorResistancePlasma,
    ArmorThresholdShock,
    ArmorResistanceShock,
    ArmorThresholdCorruption,
    ArmorResistanceCorruption,
    ArmorThresholdNRay,
    ArmorResistanceNRay,
    ArmorThresholdFrost,
    ArmorResistanceFrost,
    ModType,
    ModSlot,
    HealthRestored,
    InhalerCharge,
    ArmorTypeEffect,
    ArmorSkillBonus,
    ArmorType,
    Durability,
    Count,
};

