#pragma once
#include "CoreMinimal.h"
#include "EKeybindSetting.generated.h"

UENUM(BlueprintType)
enum class EKeybindSetting : uint8 {
    CameraPerspective,
    ShoulderSwap,
    PrimaryAction,
    SecondaryAction,
    TertiaryAction,
    NextAction,
    PreviousAction,
    Favorite,
    Sort,
    Compare,
    RadialConfirm,
    RadialCancel,
    ToggleQuests,
    MapCenter,
    PlayPauseMovie,
    RestartMovie,
    StopAudioLog,
    Confirm,
    Back,
    Exit,
    MaxAction,
    MinAction,
    MajorCategoryNext,
    MajorCategoryPrevious,
    MinorCategoryNext,
    MinorCategoryPrevious,
    ScrollUp,
    ScrollDown,
    Skip,
    Conversation1,
    Conversation2,
    Conversation3,
    Conversation4,
    Conversation5,
    Conversation6,
    Conversation7,
    Conversation8,
    Conversation9,
    LeftMouseNative,
    RightMouseNative,
    PauseMenu,
    InteractAndReload,
    SecondaryInteractAndCompanionAttack,
    NextWeaponAndWeaponRadial,
    ToggleFlashlightAndShoulder,
    CompanionAttackAndPerspective,
    Invalid,
};

