#pragma once
#include "CoreMinimal.h"
#include "EPlayerAudioEvent.generated.h"

UENUM(BlueprintType)
enum class EPlayerAudioEvent : uint8 {
    None,
    TacticalTimeDilation,
    EndTacticalTimeDilation,
    CalledShot,
    CalledShotImpactClose,
    CalledShotImpactFar,
    CalledShotCameraCutToTarget,
    CalledShotEnd,
    CalledShotOffCooldown,
    KillCamera,
    QuestStarted,
    QuestCompleted,
    QuestFailed,
    ObjectiveCompleted,
    ObjectiveFailed,
    AddendumAdded,
    ObjectiveUpdated,
    CombatStart,
    BlockRangedAttack,
    BlockMeleeAttack,
    Bribe,
    DisguiseMeter,
    DisguiseMeterDrain,
    DisguiseMeterDepleted,
    DisguiseMeterRefilled,
    PickPocketStart,
    PickPocketSuccess,
    PickPocketFail,
    PickPocketStop,
    HackStart,
    HackSuccess,
    HackFail,
    WeaponDamaged,
    WeaponSeverelyDamaged,
    WeaponDestroyed,
    HelmetDamaged,
    HelmetSeverelyDamaged,
    HelmetDestroyed,
    ArmorDamaged,
    ArmorSeverelyDamaged,
    ArmorDestroyed,
    StealthEntered,
    StealthExited,
    ReloadFail,
    MultiJumpSuccess,
    MultiJumpFail,
    SlideStart,
    SlideStop,
    SlideDownLadder,
    CompanionReviveStart,
    CompanionReviveSuccess,
    CompanionReviveStop,
};

