#include "WeaponAnimationsTPV.h"

UWeaponAnimationsTPV::UWeaponAnimationsTPV() {
    this->CombatAimBlendSpace = NULL;
    this->CombatIdle = NULL;
    this->ForwardBlendSpace = NULL;
    this->ForwardBlendMin = -50.00f;
    this->ForwardBlendMax = 50.00f;
    this->BackwardBlendSpace = NULL;
    this->BackwardBlendMin = 140.00f;
    this->BackwardBlendMax = 220.00f;
    this->LeftBlendSpace = NULL;
    this->LeftBlendMin = -140.00f;
    this->LeftBlendMax = -40.00f;
    this->RightBlendSpace = NULL;
    this->RightBlendMin = 40.00f;
    this->RightBlendMax = 140.00f;
    this->CombatCrouchStartSequence = NULL;
    this->CombatCrouchIdleSequence = NULL;
    this->CombatCrouchEndSequence = NULL;
    this->ReadyFireArmPose = NULL;
    this->IdleFireArmPose = NULL;
    this->WeaponDownWalkArm = NULL;
    this->WeaponDownRunArm = NULL;
    this->ReadyFireDelay = 0.75f;
    this->BlockStartSequence = NULL;
    this->BlockIdleSequence = NULL;
    this->SearchingStartSequence = NULL;
    this->GetUpFromFaceDownPose.AddDefaulted(1);
    this->GetUpFromFaceUpPose.AddDefaulted(1);
    this->ThrowAnimation = NULL;
    this->ThrowAnimation_FullHeightCover_OverTop = NULL;
    this->ThrowAnimation_FullHeightCover_Left = NULL;
    this->ThrowAnimation_FullHeightCover_Right = NULL;
    this->ThrowAnimation_HalfHeightCover_OverTop = NULL;
    this->ThrowAnimation_HalfHeightCover_Left = NULL;
    this->ThrowAnimation_HalfHeightCover_Right = NULL;
    this->ThrowAnimation_FullHeightCover_OverTop_RM = NULL;
    this->ThrowAnimation_FullHeightCover_Left_RM = NULL;
    this->ThrowAnimation_FullHeightCover_Right_RM = NULL;
    this->ThrowAnimation_HalfHeightCover_OverTop_RM = NULL;
    this->ThrowAnimation_HalfHeightCover_Left_RM = NULL;
    this->ThrowAnimation_HalfHeightCover_Right_RM = NULL;
    this->ThrowNearRadius = 2000.00f;
    this->ThrowAnimation_Near = NULL;
    this->ThrowAnimation_Near_FullHeightCover_OverTop = NULL;
    this->ThrowAnimation_Near_FullHeightCover_Left = NULL;
    this->ThrowAnimation_Near_FullHeightCover_Right = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_OverTop = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_Left = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_Right = NULL;
    this->ThrowAnimation_Near_FullHeightCover_OverTop_RM = NULL;
    this->ThrowAnimation_Near_FullHeightCover_Left_RM = NULL;
    this->ThrowAnimation_Near_FullHeightCover_Right_RM = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_OverTop_RM = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_Left_RM = NULL;
    this->ThrowAnimation_Near_HalfHeightCover_Right_RM = NULL;
    this->DistractionAnimations = NULL;
    this->NonCombatWeaponUpArmPose = NULL;
    this->AuthoredWalkSpeed = 144.00f;
    this->AuthoredRunSpeed = 480.00f;
    this->RunSpeedThreshold = -1.00f;
    this->StartledAnimation = NULL;
    this->AlertedToCautiousAnimation = NULL;
    this->CautiousToUnawareAnimation = NULL;
    this->PowerUpAnimation = NULL;
    this->MeleeRecoveryMontage = NULL;
    this->LeapAnimation = NULL;
    this->LeapForwardAnimation = NULL;
    this->LeapBackAnimation = NULL;
    this->LeapLeftAnimation = NULL;
    this->LeapRightAnimation = NULL;
    this->bHolsterWeaponWhenNotInCombat = false;
    this->HolsterSocket = TEXT("r_waist_att_JNT");
    this->CombatUnholsterDelay = 0.50f;
    this->bMoveWeaponBoneToRightHand = false;
    this->MeleeBoneToMove = TEXT("weapon_body_NSK");
    this->RightHandBoneToMoveWeaponTo = TEXT("r_weapon_NSK");
}


