#pragma once
#include "CoreMinimal.h"
#include "SlotInfo.h"
#include "AutoGeneratedProxyData.generated.h"

class AActor;
class AAnimationProxyActor;
class UPrimitiveComponent;

USTRUCT(BlueprintType)
struct OEIANIMPROXYRUNTIME_API FAutoGeneratedProxyData {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<int32> AutoAssignedIgnoreEntryPointSlots;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSet<TSoftObjectPtr<AActor>> ActorsToIgnore;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, Export, meta=(AllowPrivateAccess=true))
    TSet<TSoftObjectPtr<UPrimitiveComponent>> ComponentsToIgnore;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<FSlotInfo> ValidSlots;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<FSlotInfo> InvalidSlots;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<AAnimationProxyActor*> LinkedAnimationProxies;
    
    FAutoGeneratedProxyData();
};

